name: comment
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Matrix Plot: \n" >> report.md
          pip install -r requirements.txt
          python plot_matrix.py
          cml-publish example.jpg --md >> report.md
          cml-send-comment report.md